### ISSUE TITLE
ediff clarification

### ISSUE THREAD

**Issue by kaushalmodi** [justbur/emacs-vdiff#3]
In the Readme, you mention

> In ediff you control the diffed buffers through a third control buffer, which works great until you want to edit the buffers directly.

I do not understand your ediff workflow. You can always edit the buffers being ediff'd without quitting ediff. Then once back in the control window, hit `!` to update the diffs and proceed.

**Comment by justbur** [comment]
Yes, I know you can do that, but if you want to make a bunch of manual changes in buffer a, including scrolling through the buffers, and you want to see the corresponding lines in the other buffer this is awkward in ediff in my opinion. 

ediff is great for merge conflicts, but there are certain cases where I prefer something like vimdiff. In any case, I removed the comparison from the README, because it's not my intention to offend ediff users or suggest that one is always better.

**Comment by kaushalmodi** [comment]
Sure, no offense is taken. I like understanding different flows.
